_wandb:
    value:
        cli_version: 0.20.0
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 80
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 80
            "3":
                - 13
                - 55
            "4": 3.12.10
            "5": 0.20.0
            "6": 4.52.4
            "8":
                - 3
            "12": 0.20.0
            "13": windows-amd64
